// packages/split-panel/src/components/SplitPanel.tsx
import { debounce } from "es-toolkit";
import { type ReactNode, useCallback, useEffect, useRef } from "react";

interface SplitPanelProps {
  rightPanel: ReactNode;
  leftPanel: ReactNode;
}

const medianWidth = 10;
export function SplitPanel({ rightPanel, leftPanel }: SplitPanelProps) {
  const splitPanelRef = useRef<HTMLDivElement | null>(null);
  const splitPanelRec = useRef<DOMRect | null>(null);
  const medianRef = useRef<HTMLDivElement>(null);

  const resizing = useRef(false);

  useEffect(() => {
    const handlePointerDown = (event: PointerEvent) => {
      event.stopPropagation();
      resizing.current = true;
      splitPanelRef.current?.setAttribute("data-resizing", "true");
    };
    medianRef.current?.addEventListener("pointerdown", handlePointerDown);

    return () => {
      medianRef.current?.removeEventListener("pointerdown", handlePointerDown);
    };
  }, []);

  useEffect(() => {
    const handlePointerUp = (event: PointerEvent) => {
      event.stopPropagation();
      resizing.current = false;
      splitPanelRef.current?.setAttribute("data-resizing", "false");
    };
    medianRef.current?.addEventListener("pointerup", handlePointerUp);

    return () => {
      medianRef.current?.removeEventListener("pointerup", handlePointerUp);
    };
  }, []);

  useEffect(() => {
    const handleMouseMove = (event: MouseEvent) => {
      if (resizing.current && splitPanelRef.current) {
        if (splitPanelRec.current && splitPanelRec.current.width > 700) {
          const newMedianLeft = event.clientX - splitPanelRec.current.left;
          splitPanelRef.current.style.gridTemplateColumns = `calc(${newMedianLeft}px - ${medianWidth / 2}px) ${medianWidth}px 1fr`;
        }
        if (splitPanelRec.current && splitPanelRec.current.width < 700) {
          const newMedianTop = event.clientY - splitPanelRec.current.top;
          splitPanelRef.current.style.gridTemplateRows = `calc(${newMedianTop}px - ${medianWidth / 2}px) ${medianWidth}px 1fr`;
        }
      }
    };
    splitPanelRef.current?.addEventListener("mousemove", handleMouseMove);

    return () => {
      splitPanelRef.current?.removeEventListener("mousemove", handleMouseMove);
    };
  }, []);

  const handleInit = useCallback((element: HTMLDivElement | null) => {
    if (!element) return;

    const rect = element.getBoundingClientRect();
    splitPanelRef.current = element;
    splitPanelRec.current = rect;

    if (rect.width > 700) {
      element.setAttribute("data-direction", "col");
    } else {
      element.setAttribute("data-direction", "row");
    }
  }, []);

  useEffect(() => {
    if (splitPanelRef.current === null) return;

    const handleResize = debounce(() => {
      if (splitPanelRef.current) {
        const rect = splitPanelRef.current.getBoundingClientRect();
        splitPanelRec.current = rect;

        if (rect.width > 700) {
          splitPanelRef.current.setAttribute("data-direction", "col");
          splitPanelRef.current.style.removeProperty("grid-template-rows");
          splitPanelRef.current.style.removeProperty("grid-template-columns");
        } else {
          splitPanelRef.current.setAttribute("data-direction", "row");
          splitPanelRef.current.style.removeProperty("grid-template-rows");
          splitPanelRef.current.style.removeProperty("grid-template-columns");
        }
      }
    }, 100);

    const resizer = new ResizeObserver(handleResize);
    resizer.observe(splitPanelRef.current);

    return () => {
      resizer.disconnect();
    };
  }, []);

  return (
    <>
      <style>
        {`
        #mapka-split-panel[data-direction=col] { 
          display: grid;
          grid-template-columns: 1fr 10px 1fr;
          grid-template-rows: 1fr;
          min-height: 100%;
          max-height: 100%;
          min-width: 100%;
          max-width: 100%;
        }
        #mapka-split-panel([data-resizing=true][data-direction=col]){ cursor: col-resize; }
        #mapka-split-panel[data-direction=row] { 
          display: grid;
          grid-template-columns: 1fr;
          grid-template-rows: 1fr 10px 1fr;
          min-height: 100%;
          max-height: 100%;
          min-width: 100%;
          max-width: 100%;
        }
        #mapka-split-panel([data-resizing=true][data-direction=row]){ cursor: row-resize; }
        
        #mapka-split-panel([resizing]){ 
          user-select: none; 
        }
        #mapka-split-panel[data-direction=col] #median {
          inline-size: 10px;
          grid-column: 2 / 3; 
          background: grey;
        }
        #mapka-split-panel[data-direction=row] #median {
          block-size: 10px;
          grid-row: 2 / 3; 
          background: grey;
        }
        #mapka-split-panel[data-direction=col] #median:hover { 
          cursor: col-resize; 
        }
        #mapka-split-panel[data-direction=row] #median:hover { 
          cursor: row-resize; 
        }
        #mapka-split-panel[data-direction=col] #left-panel { 
          grid-column: 1 / 2; 
          grid-row: 1 / 1;
        }
        #mapka-split-panel[data-direction=row] #left-panel { 
          grid-column: 1 / 1; 
          grid-row: 1 / 2;
          max-width: 100%;
          overflow: hidden;
        }
        #mapka-split-panel[data-direction=col] #right-panel { 
          grid-column: 3 / 4; 
          grid-row: 1 / 1; 
          max-width: 100%;
          overflow: hidden;
        }
        #mapka-split-panel[data-direction=row] #right-panel { 
          grid-column: 1 / 1; 
          grid-row: 3 / 4; 
        }
        `}
      </style>
      <div id="mapka-split-panel" data-direction="col" ref={handleInit}>
        <div id="left-panel">{leftPanel}</div>
        <div id="median" ref={medianRef} />
        <div id="right-panel">{rightPanel}</div>
      </div>
    </>
  );
}

// packages/split-panel/src/web-components/SplitPanel.ts
import { debounce } from "es-toolkit";

const medianWidth = 10;
const mobileColumns = "100% 0px 100%";
const desktopColumns = `1fr ${medianWidth}px 1fr`;

export const renderShadow = (el: HTMLElement, html: string, css?: string) => {
  if (el.shadowRoot) {
    return;
  }
  const shadow = el.attachShadow({ mode: "open" });
  shadow.innerHTML = css ? `<style>${css}</style>${html}` : `${html}`;
};

export class SplitPanel extends HTMLElement {
  #isResizing = false;
  isMobileView: boolean | null = null;
  visiblePanel: "map" | "content" = "map";

  rec: DOMRect | null = null;
  median!: HTMLDivElement;
  mapPanel!: HTMLDivElement;
  contentPanel!: HTMLDivElement;

  set isResizing(value) {
    this.#isResizing = value;
    if (value) {
      this.setAttribute("resizing", "");
    } else {
      this.style.userSelect = "";
      this.style.cursor = "";
      this.removeAttribute("resizing");
    }
  }
  get isResizing() {
    return this.#isResizing;
  }

  cacheDom = () => {
    if (!this.shadowRoot) {
      return;
    }
    this.median = this.shadowRoot.querySelector("#median") as HTMLDivElement;
    this.mapPanel = this.querySelector('[slot="map-panel"]') as HTMLDivElement;
    this.contentPanel = this.querySelector('[slot="content-panel"]') as HTMLDivElement;
  };

  updateRec = () => {
    this.rec = this.getBoundingClientRect();
  };

  switchToMobile = () => {
    this.isMobileView = true;
    this.style.gridTemplateColumns = mobileColumns;
    this.style.overflowX = "hidden";
  };

  switchDesktop = () => {
    this.isMobileView = false;
    this.style.gridTemplateColumns = desktopColumns;
    this.style.overflowX = "auto";
    this.mapPanel.style.transform = "none";
    this.contentPanel.style.transform = "none";
  };

  handleResolution = () => {
    if (window.innerWidth < 1024 && this.style.gridTemplateColumns !== mobileColumns) {
      this.switchToMobile();
    }
    if (window.innerWidth > 1024 && this.style.gridTemplateColumns !== desktopColumns) {
      this.switchDesktop();
    }
  };

  handleWindowResize = debounce(() => {
    this.updateRec();
    this.handleResolution();
  }, 500);

  handlePointerdown = (event: PointerEvent) => {
    event.stopPropagation();
    this.isResizing = true;
    this.addEventListener("pointermove", this.handleResizeDrag);
    this.addEventListener("pointerup", this.handlePointerup);
  };
  handlePointerup = (event: PointerEvent) => {
    event.stopPropagation();
    this.isResizing = false;
    this.removeEventListener("pointermove", this.handleResizeDrag);
    this.removeEventListener("pointerup", this.handlePointerup);
  };

  handleResizeDrag = (e: PointerEvent) => {
    e.stopPropagation();
    if (this.rec) {
      const newMedianLeft = e.clientX - this.rec.left;
      this.style.gridTemplateColumns = `calc(${newMedianLeft}px - ${medianWidth / 2}px) ${medianWidth}px 1fr`;
    }
  };

  attachLocalEvents = () => {
    this.median.addEventListener("pointerdown", this.handlePointerdown);
  };

  attachEvents = () => {
    window.addEventListener("resize", this.handleWindowResize);
    window.addEventListener("loaded", this.handleResolution);
  };

  disconnectEvents = () => {
    window.removeEventListener("resize", this.handleWindowResize);
    window.removeEventListener("loaded", this.handleResolution);
  };

  connectedCallback() {
    this.render();
    this.cacheDom();
    this.attachEvents();
    this.attachLocalEvents();
    this.updateRec();
    this.handleResolution();
  }

  disconnectedCallback(): void {
    this.disconnectEvents();
  }

  static styles = ` 
    :host { 
      display: grid;
      min-height: 100%;
      max-height: 100%;
      min-width: 100%;
      max-width: 100%;
    }
    :host([resizing]){ 
      user-select: none; 
    }
    :host([resizing]){ 
      cursor: col-resize; 
    }
    :host { 
      grid-template-columns: ${desktopColumns};
      grid-template-rows: 1fr;
    }
    :host #median {
      inline-size: ${medianWidth}px;
      grid-column: 2 / 3; 
    }
    :host #median:hover { 
      cursor: col-resize; 
    }
    slot[name="map-panel"] { 
      grid-column: 1 / 2; 
      grid-row: 1 / 1;
    }
    slot[name="content-panel"] { 
      grid-column: 3 / 4; 
      grid-row: 1 / 1; 
    }
    :host([resizing][direction=col]){ cursor: row-resize; }

    #median { 
      background: #ccc; 
      width: ${medianWidth}px;
      background: grey;
    }
    ::slotted(*) { overflow: auto; }
  `;

  static html = `
    <slot id="map-panel" name="map-panel"></slot>
    <div id="median" part="median"></div>
    <slot id="content-panel" name="content-panel"></slot>
  `;

  render() {
    renderShadow(this, SplitPanel.html, SplitPanel.styles);
  }
}
